name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build first Docker image
      run: docker build . --file Dockerfile1 --tag rfd1/cms1:latest

    - name: Push first docker image
      run: docker push rfd1/cms1:latest

    - name: Build second Docker image
      run: docker build . --file Dockerfile1-latex --tag rfd1/cms1-latex:latest

    - name: Push second docker image
      run: docker push rfd1/cms1-latex:latest
      
